FROM node:16.14.0-slim

RUN apt-get -y update
RUN apt-get -y install vim

WORKDIR /opt/www

COPY ./package*.json ./
COPY ./yarn.lock ./

RUN yarn

COPY ./ ./

RUN yarn build

RUN chmod +x ./bin.local/start.sh
CMD ["sh", "./bin.local/start.sh"]